on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
name: Deploy website on push to master branch
jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Get latest code
      uses: actions/checkout@v3
    
    - name: Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.3.2
      with:
        server: 185.146.238.70
        username: ${{ secrets.ftp_username }}
        password: ${{ secrets.ftp_password }}
        server-dir: httpdocs/
        exclude: |
          **/.git*
          **/.git*/**
